export const dom = {
  feedList: document.getElementById('feed-list'),
  feedScrollLeftBtn: document.getElementById('feed-scroll-left'),
  feedScrollRightBtn: document.getElementById('feed-scroll-right'),
  feedListEmpty: document.getElementById('feed-list-empty'),
  articleList: document.getElementById('article-list'),
  stateEmpty: document.getElementById('state-empty'),
  stateLoading: document.getElementById('state-loading'),
  bannerRegion: document.getElementById('banner-region'),
  contentTitle: document.getElementById('content-title'),
  feedItemTemplate: document.getElementById('feed-item-template'),
  articleItemTemplate: document.getElementById('article-item-template'),
  navAllArticles: document.getElementById('nav-all-articles'),
  navStarred: document.getElementById('nav-starred'),
  pagination: document.getElementById('pagination'),
  searchInput: document.getElementById('search-input'),

  addFeedDialog: document.getElementById('add-feed-dialog'),
  addFeedForm: document.getElementById('add-feed-form'),
  feedUrlInput: document.getElementById('feed-url-input'),
  addFeedError: document.getElementById('add-feed-error'),
  openAddFeedBtn: document.getElementById('open-add-feed'),
  cancelAddFeedBtn: document.getElementById('cancel-add-feed'),
  submitAddFeedBtn: document.getElementById('submit-add-feed'),
  stateEmptyCta: document.getElementById('state-empty-cta'),
  refreshAllBtn: document.getElementById('refresh-all-feeds'),

  confirmDialog: document.getElementById('confirm-dialog'),
  confirmTitle: document.getElementById('confirm-title'),
  confirmMessage: document.getElementById('confirm-message'),
  confirmActionBtn: document.getElementById('confirm-action-btn'),
  confirmCancelBtn: document.getElementById('confirm-cancel-btn'),
};