export const dom = {
  feedList: document.getElementById('feed-list'),
  feedScrollLeftBtn: document.getElementById('feed-scroll-left'),
  feedScrollRightBtn: document.getElementById('feed-scroll-right'),
  feedListEmpty: document.getElementById('feed-list-empty'),
  articleList: document.getElementById('article-list'),
  stateEmpty: document.getElementById('state-empty'),
  stateLoading: document.getElementById('state-loading'),
  bannerRegion: document.getElementById('banner-region'),
  contentTitle: document.getElementById('content-title'),
  feedItemTemplate: document.getElementById('feed-item-template'),
  articleItemTemplate: document.getElementById('article-item-template'),
  navAllArticles: document.getElementById('nav-all-articles'),
  navStarred: document.getElementById('nav-starred'),
  pagination: document.getElementById('pagination'),
  searchInput: document.getElementById('search-input'),

  addFeedDialog: document.getElementById('add-feed-dialog'),
  addFeedForm: document.getElementById('add-feed-form'),
  feedUrlInput: document.getElementById('feed-url-input'),
  addFeedError: document.getElementById('add-feed-error'),
  openAddFeedBtn: document.getElementById('open-add-feed'),
  cancelAddFeedBtn: document.getElementById('cancel-add-feed'),
  submitAddFeedBtn: document.getElementById('submit-add-feed'),
  stateEmptyCta: document.getElementById('state-empty-cta'),
  refreshAllBtn: document.getElementById('refresh-all-feeds'),

  confirmDialog: document.getElementById('confirm-dialog'),
  confirmTitle: document.getElementById('confirm-title'),
  confirmMessage: document.getElementById('confirm-message'),
  confirmActionBtn: document.getElementById('confirm-action-btn'),
  confirmCancelBtn: document.getElementById('confirm-cancel-btn'),

  authScreen: document.getElementById('auth-screen'),
  appRoot: document.querySelector('.app'),
  authTabLogin: document.getElementById('auth-tab-login'),
  authTabRegister: document.getElementById('auth-tab-register'),
  loginForm: document.getElementById('login-form'),
  loginEmail: document.getElementById('login-email'),
  loginPassword: document.getElementById('login-password'),
  loginError: document.getElementById('login-error'),
  loginSuccess: document.getElementById('login-success'),
  loginSubmit: document.getElementById('login-submit'),
  registerForm: document.getElementById('register-form'),
  registerName: document.getElementById('register-name'),
  registerEmail: document.getElementById('register-email'),
  registerPassword: document.getElementById('register-password'),
  registerError: document.getElementById('register-error'),
  registerSubmit: document.getElementById('register-submit'),

  guestBadge: document.getElementById('guest-badge'),
  sidebarUserName: document.getElementById('topbar-user-name'),
  sidebarLoginBtn: document.getElementById('topbar-login-btn'),
  logoutBtn: document.getElementById('topbar-logout-btn'),
  navPlaylists: document.getElementById('nav-playlists'),
  countAllArticles: document.getElementById('count-all-articles'),
  countStarred: document.getElementById('count-starred'),
  countPlaylists: document.getElementById('count-playlists'),
  sidebarFeedsSection: document.getElementById('sidebar-feeds-section'),
  sidebarPlaylistsSection: document.getElementById('sidebar-playlists-section'),
  sidebarNewPlaylistBtn: document.getElementById('sidebar-new-playlist-btn'),

  // Playlists
  playlistList: document.getElementById('playlist-list'),
  playlistListEmpty: document.getElementById('playlist-list-empty'),
  newPlaylistBtn: document.getElementById('new-playlist-btn'),
  playlistItemTemplate: document.getElementById('playlist-item-template'),

  createPlaylistDialog: document.getElementById('create-playlist-dialog'),
  createPlaylistForm: document.getElementById('create-playlist-form'),
  playlistNameInput: document.getElementById('playlist-name-input'),
  createPlaylistError: document.getElementById('create-playlist-error'),
  cancelCreatePlaylistBtn: document.getElementById('cancel-create-playlist'),
  submitCreatePlaylistBtn: document.getElementById('submit-create-playlist'),

  playlistPickerDialog: document.getElementById('playlist-picker-dialog'),
  playlistPickerList: document.getElementById('playlist-picker-list'),
  playlistPickerEmpty: document.getElementById('playlist-picker-empty'),
  playlistPickerNewBtn: document.getElementById('playlist-picker-new'),
  playlistPickerDoneBtn: document.getElementById('playlist-picker-done'),

  playlistToolbar: document.getElementById('playlist-toolbar'),
  playlistFeedUrl: document.getElementById('playlist-feed-url'),
  copyPlaylistFeedUrlBtn: document.getElementById('copy-playlist-feed-url'),
  deletePlaylistBtn: document.getElementById('delete-playlist-btn'),

  onboardingDialog: document.getElementById('onboarding-dialog'),
  onboardingList: document.getElementById('onboarding-list'),
  onboardingSkipBtn: document.getElementById('onboarding-skip'),

  backToTopBtn: document.getElementById('back-to-top'),
};